/**
 * cryptoLayer.js — Base Encryption Engine (RUN 6)
 *
 * All cryptographic primitives used by the system.
 * Uses only Web Crypto API (SubtleCrypto) — zero external dependencies.
 *
 * Algorithm choices:
 *   Key derivation: PBKDF2 (100,000 iterations, SHA-256)
 *   Encryption:     AES-GCM 256-bit with random 12-byte IV per operation
 *   Integrity:      Built into AES-GCM (authenticated encryption)
 *
 * SSOT Rules:
 * ✔ Pure crypto primitives — no storage, no state
 * ✔ Every function is independently testable
 * ✔ Never stores keys or plaintext
 * ❌ Never imports from other RUN 6 modules (no circular deps)
 */

// ─── Constants ────────────────────────────────────────────────────────────────

const ALGO        = "AES-GCM";
const KEY_LENGTH  = 256;
const IV_BYTES    = 12;
const SALT_BYTES  = 16;
const PBKDF2_ITER = 100_000;
const PBKDF2_HASH = "SHA-256";

// ─── Key Derivation ───────────────────────────────────────────────────────────

/**
 * Derive a CryptoKey from a passphrase using PBKDF2.
 * Returns a non-extractable AES-GCM key.
 *
 * @param {string}     password
 * @param {Uint8Array} salt      - 16 random bytes (generated by generateSalt)
 * @returns {Promise<CryptoKey>}
 */
export async function deriveKey(password, salt) {
  const enc = new TextEncoder();

  const rawKey = await crypto.subtle.importKey(
    "raw",
    enc.encode(password),
    { name: "PBKDF2" },
    false,
    ["deriveKey"]
  );

  return crypto.subtle.deriveKey(
    { name: "PBKDF2", salt, iterations: PBKDF2_ITER, hash: PBKDF2_HASH },
    rawKey,
    { name: ALGO, length: KEY_LENGTH },
    false,           // non-extractable
    ["encrypt", "decrypt"]
  );
}

/**
 * Generate a cryptographically random salt.
 * Must be stored alongside ciphertext (not secret).
 *
 * @returns {Uint8Array}
 */
export function generateSalt() {
  return crypto.getRandomValues(new Uint8Array(SALT_BYTES));
}

/**
 * Generate a random IV for AES-GCM.
 * Must be stored alongside ciphertext (not secret).
 *
 * @returns {Uint8Array}
 */
export function generateIV() {
  return crypto.getRandomValues(new Uint8Array(IV_BYTES));
}

// ─── Encrypt ──────────────────────────────────────────────────────────────────

/**
 * Encrypt arbitrary data with a CryptoKey.
 *
 * @param {any}        data      - Any JSON-serializable value
 * @param {CryptoKey}  key       - From deriveKey()
 * @returns {Promise<EncryptedPayload>}
 *
 * @typedef {object} EncryptedPayload
 * @property {string} ciphertext - Base64-encoded ciphertext
 * @property {string} iv         - Base64-encoded IV
 * @property {number} version    - Schema version for future migration
 */
export async function encryptData(data, key) {
  const iv      = generateIV();
  const encoded = new TextEncoder().encode(JSON.stringify(data));

  const encrypted = await crypto.subtle.encrypt(
    { name: ALGO, iv },
    key,
    encoded
  );

  return {
    ciphertext: _bufToB64(encrypted),
    iv:         _bufToB64(iv),
    version:    1
  };
}

// ─── Decrypt ──────────────────────────────────────────────────────────────────

/**
 * Decrypt an EncryptedPayload with a CryptoKey.
 *
 * @param {EncryptedPayload} payload
 * @param {CryptoKey}        key
 * @returns {Promise<any>} Original data value
 * @throws {CryptoDecryptError} If key is wrong or data tampered
 */
export async function decryptData(payload, key) {
  const { ciphertext, iv } = payload;

  let decrypted;
  try {
    decrypted = await crypto.subtle.decrypt(
      { name: ALGO, iv: _b64ToBuf(iv) },
      key,
      _b64ToBuf(ciphertext)
    );
  } catch {
    throw new CryptoDecryptError("Decryption failed — wrong passphrase or corrupted data");
  }

  try {
    return JSON.parse(new TextDecoder().decode(decrypted));
  } catch {
    throw new CryptoDecryptError("Decryption succeeded but payload could not be parsed");
  }
}

// ─── Hashing (non-reversible — for verification only) ────────────────────────

/**
 * Hash a passphrase with PBKDF2 for stored verification.
 * NOT the same as a session key — used to verify password without decrypting vault.
 *
 * @param {string}     password
 * @param {Uint8Array} salt
 * @returns {Promise<string>} Base64 hash
 */
export async function hashPassword(password, salt) {
  const enc = new TextEncoder();
  const raw = await crypto.subtle.importKey(
    "raw", enc.encode(password), { name: "PBKDF2" }, false, ["deriveBits"]
  );
  const bits = await crypto.subtle.deriveBits(
    { name: "PBKDF2", salt, iterations: PBKDF2_ITER, hash: PBKDF2_HASH },
    raw,
    256
  );
  return _bufToB64(bits);
}

// ─── Encode / Decode Helpers ──────────────────────────────────────────────────

/**
 * Encode a CryptoKey-safe Uint8Array salt/IV to a storable Base64 string.
 */
export function encodeSalt(bytes) {
  return _bufToB64(bytes);
}

/**
 * Decode a stored Base64 salt/IV back to Uint8Array.
 */
export function decodeSalt(b64) {
  return _b64ToBuf(b64);
}

// ─── Custom Error ─────────────────────────────────────────────────────────────

export class CryptoDecryptError extends Error {
  constructor(msg) {
    super(msg);
    this.name = "CryptoDecryptError";
  }
}

// ─── Internal ─────────────────────────────────────────────────────────────────

function _bufToB64(buf) {
  return btoa(String.fromCharCode(...new Uint8Array(buf)));
}

function _b64ToBuf(b64) {
  const bin = atob(b64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);
  return arr.buffer;
}
